# Generated by Django 3.2.13 on 2022-05-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='weight',
            new_name='brand',
        ),
        migrations.AddField(
            model_name='item',
            name='unit_Count',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='unit_weight',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
