# Generated by Django 3.2.13 on 2022-05-18 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='inventory',
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='logistics.warehouse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='state',
            field=models.CharField(max_length=200),
        ),
    ]
